baseURL = "https://bf.shoogle.net/burkina-faso/"
languageCode = "fr"
title = "Burkina Faso"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "burkina-faso"

[taxonomies]
  shop = "shops"
